export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  CALLS = 'CALLS_SERVICE',
  SCHEDULER = 'SCHEDULER_SERVICE',
  SENDGRID_CLIENT = 'SENDGRID_CLIENT',
  SENDGRID_SERVICE = 'SENDGRID_SERVICE',
  TOKEN_SERVICE = 'TOKEN_SERVICE',
  TWILIO_SERVICE = 'TWILIO_SERVICE',
  TWILIO_CLIENT = 'TWILIO_CLIENT',
  USER = 'USER_SERVICE',
  VERIFY = 'VERIFY_SERVICE',
  WEBHOOKS = 'WEBHOOKS_SERVICE',
}

export enum ROUTES {
  AUTH = 'auth',
  CALLS = 'calls',
  USER = 'users',
  WEBHOOKS = 'webhooks',
  VERIFY = 'verify',
}
