export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  CALLS = 'CALLS_SERVICE',
  SCHEDULER = 'SCHEDULER',
  TWILIO_SERVICE = 'TWILIO_SERVICE',
  TWILIO_CLIENT = 'TWILIO_CLIENT',
  USER = 'USER_SERVICE',
  WEBHOOKS = 'WEBHOOKS_SERVICE',
}

export enum ROUTES {
  AUTH = 'auth',
  CALLS = 'calls',
  USER = 'users',
  WEBHOOKS = 'webhooks',
}
