export enum SERVICES {
  CALLS = 'CALLS_SERVICE',
  WEBHOOKS = 'WEBHOOKS_SERVICE',
  TWILIO_SERVICE = 'TWILIO_SERVICE',
  TWILIO_CLIENT = 'TWILIO_CLIENT',
}

export enum ROUTES {
  CALLS = 'calls',
  WEBHOOKS = 'webhooks',
}
